-keepnames class * implements android.os.Parcelable {public static final ** CREATOR;}
-keep class com.saradabar.** {*;}
-keep class jp.co.benesse.dcha.dchaservice.IDchaService
-keep class org.zeroturnaround.** {*;}
-dontwarn androidx.annotation.**
-dontwarn org.slf4j.impl.**
-keep class android.support.v4.app.CoreComponentFactory {*;}
